# Site settings
title: "Mapping the Past: A Spatial History of the United States"
baseurl: "" # the subpath of your site, e.g. /blog
url: "mtp2016.cameronblevins.org" # the base hostname & protocol for your site
twitter_username: historying
github_username:  cblevins
university: Rutgers University
course_number: "History 506:303"
semester: "Spring 2016"
room: "Scott Hall 215 (43 College Ave.)"
meetingtime: "Wed. 9:50-12:50am"

instructor: Cameron Blevins
email: cameron.blevins@rutgers.edu
office: "Room 205 - RCHA Building (88 College Ave.)"
officehours: "Wed. 1:30pm-3:00pm, and by appointment"

# Build settings
markdown: kramdown

