# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Mapping the Past: A Spatial History of the United States"
email: cameron.blevins@rutgers.edu
description: > # this means to ignore newlines until "baseurl:"
  Course Website for Mapping the Past: A Spatial History of the United States (Rutgers University, Spring 2015)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: historying
github_username:  cblevins

# Build settings
markdown: kramdown
