# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Mapping the Past: A Spatial History of the United States"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: historying
github_username:  cblevins
university: Rutgers University
course_number: "History 506:303"
semester: "Spring 2016"
room: "Scott Hall 215 (43 College Ave.)"
meetingtime: "Wed. 9:50-12:50am"

instructor: Cameron Blevins
email: cameron.blevins@rutgers.edu
office: "Room 205, RCHA Building (88 College Ave.)"
officehours: "Wed. 1:00pm-2:00pm, and by appointment"


# Build settings
markdown: kramdown

